#!/bin/bash
sudo pkill -f "runargs.EVNTtoHITS" 2>/dev/null
sudo pkill -f "EVNTtoHITS" 2>/dev/null
sudo boinc --redirectio --dir /home/pepper &
sleep 3
boincmgr &
##(cd /var/lib/boinc-client && boinccmd --set_run_mode auto)
(cd /home/pepper && boinccmd --set_run_mode auto)
sudo systemctl start boinc-affinity.service
journalctl -fu boinc-affinity.service
