#!/bin/bash
(cd /var/lib/boinc-client && boinccmd --set_run_mode never)
sleep 10
sudo systemctl stop boinc-affinity.service
sudo pkill boincmgr
sudo pkill boinc
sudo pkill -f "runargs.EVNTtoHITS" 2>/dev/null
